language: python
python:
- 3.7
- 3.6
- 3.5
- 3.4
install: travis_wait pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ark0015
  password:
    secure: h3AQkGH7FgheRZOw9phjLeE9llm4QVaLj/Oaq9kt45RAWV9ly5nZcRrIBOByK4akdDYTFCNh1oa9azZAGFk0XhSOBcDQJobkEfxTcK0P2hWEjL6Nb1rnqSLSmegvzI52lIuny3Tq7O5YfK+n4UVHnGwsjDFPKFK6fLTcUlT7UZaXojbE+fsqwIxh5oSN54+GCHsOcpWNYpZD2X1sGV7UKY+pCHmjMxxSlTpbM3n+HTilhIF3xgkkbEQ/6IX2OAum1VmsHSdie888aZDlRfOrkhCzkPGVTv9E2tP50AQyXNQZVWrm9yvEnm+pBphJUZ/6ukt9NHv3CxGIcyb6srpUyevIDzzkFSZ8fKHdgVkfTD3t/+HXv0VII2uwicgZkg3Q7JN602Dgev17hptJ7F3ZhKhkvaJanPx7iXHINsv/CxyL4Mfr+CnNZYwkPwqbR61JX3IAMbMQp/2mWFg7s/5Kzdt4+zwjeNAkgcOGhPSEyGCUwoL29edaV9AkU/q73ic6O4m22Kj1i61veQ2fMJbmX3pNw4ymh4UVwIp1wlgM0KLBj9JQSapalvl0fvV9FQUkWCDuM2CcfQYVRSk0gKaO8if5HdHqB5l/pRsG6/d/wZuLdbp4j7qV3PYkg7nC5BDTOnke3SzqxRs1qhf95Els+REx+XR7dappLBlHnriT3SM=
  on:
    tags: true
    repo: ark0015/gwent
    python: 3.6
